# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_auto_20180225_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
