# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0005_auto_20180227_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='picture',
            name='picture',
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
