# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0006_auto_20180302_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Review',
        ),
        migrations.AddField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, upload_to='places_location'),
        ),
    ]
