# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 20:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0009_auto_20180303_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='location',
            name='visited_by',
            field=models.CharField(default=None, max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
