# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 20:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0010_auto_20180305_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='visited_by',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
