# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0011_auto_20180305_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
