# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0012_auto_20180307_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, max_length=1000, upload_to='places_location'),
        ),
    ]
